baseURL = "https://t4kuya.github.io/credate"
languageCode = "en-us"
title = "Credate"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Takuya Yamanaka"
    description = "Improved version of wc"
    githubUsername = "t4kuya"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/installation/"
    name = "Installation"
    weight = 3

[[menu.main]]
    url = "/usage/"
    name = "Usage"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/t4kuya"
    name = "fab fa-github"
    weight = 2

